# LaTeX2HTML 96.1-h (September 30, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$70%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3597" SRC="img188.gif">|; 
$key = q/{_inline}$mathcalR_P(r_P)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=57 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3099" SRC="img77.gif">|; 
$key = q/{figure}includegraphics[scale=0.7]fig_acre_v2.pslabelfig-acre{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=505 HEIGHT=611 ALIGN=BOTTOM ALT="figure2737" SRC="img233.gif">|; 
$key = q/{figure}plotoneedr_quasarccplot.pslabelfig-edr_quasarccplot{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=748 HEIGHT=338 ALIGN=BOTTOM ALT="figure2757" SRC="img237.gif">|; 
$key = q/{_inline}$i^*=20.0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3473" SRC="img174.gif">|; 
$key = q/{_inline}$(u^*-g^*),(g^*-r^*),(r^*-i^*),(i^*-z^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=286 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3429" SRC="img155.gif">|; 
$key = q/{figure}plotonefilter.pslabelfig-imagingfilters{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=735 HEIGHT=384 ALIGN=BOTTOM ALT="figure2708" SRC="img228.gif">|; 
$key = q/{deluxetable}rrrtablecaptionTheCosmicColorslabeltbl-cosmiccolortablewidth0pttableheadcolheadcolor;SPMamp;colheadvalue;SPMamp;colheadscatterstartdata_inline$(u^*-g^*)$_inline;SPMamp;1.42;SPMamp;_inline$pm$_inline0.82_inline$(g^*-r^*)$_inline;SPMamp;1.11;SPMamp;_inline$pm$_inline0.46_inline$(r^*-i^*)$_inline;SPMamp;0.48;SPMamp;_inline$pm$_inline0.34_inline$(i^*-z^*)$_inline;SPMamp;0.35;SPMamp;_inline$pm$_inline0.22data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=657 HEIGHT=476 ALIGN=BOTTOM ALT="deluxetable2320" SRC="img215.gif">|; 
$key = q/{_inline}$(u^*-g^*),(g^*-r^*),(r^*-i^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=213 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3431" SRC="img156.gif">|; 
$key = q/{_inline}$b_g^*-r^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=42 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3401" SRC="img148.gif">|; 
$key = q/{_inline}$(r^*-i^*).${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3293" SRC="img127.gif">|; 
$key = q/{deluxetable}cccctabletypesizetinytablecaptionTargetSelectionVersions:RunsandPlateslabeltbl-targettablewidth0pttablecolumns4tableheadcolheadsmallttTargetVersion;SPMamp;colheadsmallRuns;SPMamp;colheadsmallPlatestablenotemarka;SPMamp;colheadsmallttprimTargetclassstartdatav2.2.a;SPMamp;752,756;SPMamp;266-315,363;SPMamp;ttSpecObjv2.5;SPMamp;1336,39,56,59;SPMamp;349-362,366-367;SPMamp;ttSpecObjv2.7;SPMamp;94,125;SPMamp;383-416;SPMamp;ttSpecObjv2.13.8;SPMamp;all;SPMamp;all;SPMamp;ttPhotoObjdatatablenotetextaPlate324isdominatedbyaspecialselectionoftargetsinthestellarlocus.{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=701 HEIGHT=1004 ALIGN=BOTTOM ALT="deluxetable2435" SRC="img220.gif">|; 
$key = q/{_inline}$u^*g^*r^*i^*z^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=78 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2825" SRC="img8.gif">|; 
$key = q/{_inline}$i=eta+32.5arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2943" SRC="img44.gif">|; 
$key = q/{_inline}$r^*=21${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=55 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3155" SRC="img99.gif">|; 
$key = q/{_inline}$beta${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3625" SRC="img189.gif">|; 
$key = q/{deluxetable}rrrrrrrtabletypesizescriptsizetablecaptionEarlyDataReleaseSpectroscopicPlateslabeltbl-edr-spectratablecommentsUnobservedplateshavenoentryundertheDateCompletedcolumntablewidth0pttablecolumns7tableheadcolheadTileID;SPMamp;colheadPlateID;SPMamp;colheadDateCompleted;SPMamp;colheadRA(_inline$arcdeg$_inline);SPMamp;colheadDEC(_inline$arcdeg$_inline);SPMamp;colhead_inline$(SN)^2$_inlineat_inline$g^*=20.2$_inline;SPMamp;colheadSmearExposure;SPMamp;;SPMamp;colhead(MJD);SPMamp;;SPMamp;;SPMamp;colheadperpixel;SPMamp;colheadIncluded?startdata122;SPMamp;266;SPMamp;51630;SPMamp;_inline$145.8928$_inline;SPMamp;_inline$0.0613$_inline;SPMamp;33.8;SPMamp;No121;SPMamp;267;SPMamp;51608;SPMamp;_inline$147.7332$_inline;SPMamp;_inline$-0.0307$_inline;SPMamp;31.1;SPMamp;No120;SPMamp;268;SPMamp;51633;SPMamp;_inline$149.0618$_inline;SPMamp;_inline$0.0797$_inline;SPMamp;33.1;SPMamp;No119;SPMamp;269;SPMamp;51910;SPMamp;_inline$150.6295$_inline;SPMamp;_inline$0.0000$_inline;SPMamp;22.8;SPMamp;Yes118;SPMamp;270;SPMamp;51909;SPMamp;_inline$152.4607$_inline;SPMamp;_inline$0.0061$_inline;SPMamp;29.4;SPMamp;No117;SPMamp;271;SPMamp;---;SPMamp;_inline$154.2643$_inline;SPMamp;_inline$0.0245$_inline;SPMamp;---;SPMamp;---116;SPMamp;272;SPMamp;51941;SPMamp;_inline$156.0189$_inline;SPMamp;_inline$0.0184$_inline;SPMamp;24.8;SPMamp;No115;SPMamp;273;SPMamp;51957;SPMamp;_inline$157.9021$_inline;SPMamp;_inline$0.0092$_inline;SPMamp;17.9;SPMamp;No114;SPMamp;274;SPMamp;51913;SPMamp;_inline$159.7487$_inline;SPMamp;_inline$0.0184$_inline;SPMamp;65.7;SPMamp;Yes113;SPMamp;275;SPMamp;51910;SPMamp;_inline$161.4664$_inline;SPMamp;_inline$-0.0061$_inline;SPMamp;37.3;SPMamp;Yes112;SPMamp;276;SPMamp;51909;SPMamp;_inline$163.3804$_inline;SPMamp;_inline$0.0429$_inline;SPMamp;47.1;SPMamp;Yes111;SPMamp;277;SPMamp;51908;SPMamp;_inline$165.2300$_inline;SPMamp;_inline$0.0061$_inline;SPMamp;28.3;SPMamp;Yes110;SPMamp;278;SPMamp;51900;SPMamp;_inline$167.0275$_inline;SPMamp;_inline$0.0276$_inline;SPMamp;47.1;SPMamp;Yes109;SPMamp;279;SPMamp;---;SPMamp;_inline$168.8618$_inline;SPMamp;_inline$-0.0061$_inline;SPMamp;---;SPMamp;---108;SPMamp;280;SPMamp;---;SPMamp;_inline$170.4477$_inline;SPMamp;_inline$0.1655$_inline;SPMamp;---;SPMamp;---107;SPMamp;281;SPMamp;51614;SPMamp;_inline$171.8773$_inline;SPMamp;_inline$0.1104$_inline;SPMamp;40.8;SPMamp;No106;SPMamp;282;SPMamp;51658;SPMamp;_inline$173.7698$_inline;SPMamp;_inline$-0.1196$_inline;SPMamp;33.8;SPMamp;No105;SPMamp;283;SPMamp;51959;SPMamp;_inline$175.9750$_inline;SPMamp;_inline$-0.0031$_inline;SPMamp;28.6;SPMamp;No104;SPMamp;284;SPMamp;51943;SPMamp;_inline$177.9810$_inline;SPMamp;_inline$-0.0644$_inline;SPMamp;27.8;SPMamp;No103;SPMamp;285;SPMamp;51930;SPMamp;_inline$179.5608$_inline;SPMamp;_inline$-0.0153$_inline;SPMamp;44.0;SPMamp;Yes102;SPMamp;286;SPMamp;51999;SPMamp;_inline$181.3061$_inline;SPMamp;_inline$0.0092$_inline;SPMamp;16.5;SPMamp;No101;SPMamp;287;SPMamp;52023;SPMamp;_inline$183.1557$_inline;SPMamp;_inline$0.0184$_inline;SPMamp;24.9;SPMamp;No100;SPMamp;288;SPMamp;52000;SPMamp;_inline$184.8459$_inline;SPMamp;_inline$-0.0184$_inline;SPMamp;20.5;SPMamp;No99;SPMamp;289;SPMamp;51990;SPMamp;_inline$186.7078$_inline;SPMamp;_inline$-0.0184$_inline;SPMamp;22.7;SPMamp;No98;SPMamp;290;SPMamp;51941;SPMamp;_inline$188.9313$_inline;SPMamp;_inline$0.0307$_inline;SPMamp;20.4;SPMamp;No97;SPMamp;291;SPMamp;51928;SPMamp;_inline$190.7257$_inline;SPMamp;_inline$-0.0368$_inline;SPMamp;31.8;SPMamp;Yes96;SPMamp;292;SPMamp;51609;SPMamp;_inline$192.5814$_inline;SPMamp;_inline$-0.0245$_inline;SPMamp;21.4;SPMamp;No95;SPMamp;293;SPMamp;51689;SPMamp;_inline$194.4555$_inline;SPMamp;_inline$0.0031$_inline;SPMamp;22.1;SPMamp;No94;SPMamp;294;SPMamp;51986;SPMamp;_inline$196.5075$_inline;SPMamp;_inline$0.0889$_inline;SPMamp;22.8;SPMamp;No93;SPMamp;295;SPMamp;51985;SPMamp;_inline$198.0996$_inline;SPMamp;_inline$-0.0184$_inline;SPMamp;17.3;SPMamp;No92;SPMamp;296;SPMamp;51665;SPMamp;_inline$199.8694$_inline;SPMamp;_inline$0.0674$_inline;SPMamp;17.3;SPMamp;No91;SPMamp;297;SPMamp;51959;SPMamp;_inline$201.5658$_inline;SPMamp;_inline$-0.0061$_inline;SPMamp;22.0;SPMamp;Yes90;SPMamp;298;SPMamp;---;SPMamp;_inline$203.4644$_inline;SPMamp;_inline$-0.0061$_inline;SPMamp;---;SPMamp;---89;SPMamp;299;SPMamp;51671;SPMamp;_inline$205.3569$_inline;SPMamp;_inline$0.0061$_inline;SPMamp;31.9;SPMamp;No88;SPMamp;300;SPMamp;51666;SPMamp;_inline$207.2249$_inline;SPMamp;_inline$-0.0123$_inline;SPMamp;23.4;SPMamp;No87;SPMamp;301;SPMamp;51942;SPMamp;_inline$209.6201$_inline;SPMamp;_inline$-0.0552$_inline;SPMamp;30.9;SPMamp;Yes86;SPMamp;302;SPMamp;51688;SPMamp;_inline$211.7208$_inline;SPMamp;_inline$-0.0490$_inline;SPMamp;22.9;SPMamp;No85;SPMamp;303;SPMamp;51615;SPMamp;_inline$213.4171$_inline;SPMamp;_inline$0.0674$_inline;SPMamp;24.2;SPMamp;No84;SPMamp;304;SPMamp;51609;SPMamp;_inline$214.5129$_inline;SPMamp;_inline$0.0000$_inline;SPMamp;17.8;SPMamp;Yes83;SPMamp;305;SPMamp;51613;SPMamp;_inline$216.3073$_inline;SPMamp;_inline$0.0337$_inline;SPMamp;24.2;SPMamp;No82;SPMamp;306;SPMamp;51637;SPMamp;_inline$217.8810$_inline;SPMamp;_inline$-0.0828$_inline;SPMamp;30.1;SPMamp;No81;SPMamp;307;SPMamp;51663;SPMamp;_inline$219.7244$_inline;SPMamp;_inline$0.0552$_inline;SPMamp;24.9;SPMamp;No80;SPMamp;308;SPMamp;51662;SPMamp;_inline$221.6415$_inline;SPMamp;_inline$-0.0613$_inline;SPMamp;28.2;SPMamp;No79;SPMamp;309;SPMamp;51994;SPMamp;_inline$223.6321$_inline;SPMamp;_inline$0.0245$_inline;SPMamp;32.0;SPMamp;No78;SPMamp;310;SPMamp;51990;SPMamp;_inline$225.8618$_inline;SPMamp;_inline$0.0061$_inline;SPMamp;18.1;SPMamp;No77;SPMamp;311;SPMamp;51665;SPMamp;_inline$227.2822$_inline;SPMamp;_inline$0.0245$_inline;SPMamp;22.5;SPMamp;No76;SPMamp;312;SPMamp;51689;SPMamp;_inline$229.0766$_inline;SPMamp;_inline$0.0245$_inline;SPMamp;20.5;SPMamp;No75;SPMamp;313;SPMamp;51673;SPMamp;_inline$230.9047$_inline;SPMamp;_inline$-0.0215$_inline;SPMamp;22.7;SPMamp;No74;SPMamp;314;SPMamp;51641;SPMamp;_inline$232.7451$_inline;SPMamp;_inline$0.0123$_inline;SPMamp;16.3;SPMamp;No73;SPMamp;315;SPMamp;51663;SPMamp;_inline$234.5733$_inline;SPMamp;_inline$-0.0031$_inline;SPMamp;18.6;SPMamp;No97;SPMamp;324;SPMamp;51666;SPMamp;_inline$190.7257$_inline;SPMamp;_inline$-0.0368$_inline;SPMamp;20.6;SPMamp;No148;SPMamp;349;SPMamp;51699;SPMamp;_inline$254.1442$_inline;SPMamp;_inline$63.6530$_inline;SPMamp;47.4;SPMamp;No149;SPMamp;350;SPMamp;51691;SPMamp;_inline$258.4975$_inline;SPMamp;_inline$65.1336$_inline;SPMamp;21.8;SPMamp;No150;SPMamp;351;SPMamp;51780;SPMamp;_inline$255.9522$_inline;SPMamp;_inline$61.6193$_inline;SPMamp;22.0;SPMamp;No151;SPMamp;352;SPMamp;51694;SPMamp;_inline$260.0012$_inline;SPMamp;_inline$63.0373$_inline;SPMamp;19.9;SPMamp;No152;SPMamp;353;SPMamp;51703;SPMamp;_inline$257.5362$_inline;SPMamp;_inline$59.5647$_inline;SPMamp;37.1;SPMamp;No153;SPMamp;354;SPMamp;51792;SPMamp;_inline$261.3024$_inline;SPMamp;_inline$60.9272$_inline;SPMamp;15.4;SPMamp;Yes154;SPMamp;355;SPMamp;51788;SPMamp;_inline$258.9371$_inline;SPMamp;_inline$57.4932$_inline;SPMamp;28.9;SPMamp;No155;SPMamp;356;SPMamp;---;SPMamp;_inline$262.4414$_inline;SPMamp;_inline$58.8061$_inline;SPMamp;---;SPMamp;---156;SPMamp;357;SPMamp;---;SPMamp;_inline$260.1872$_inline;SPMamp;_inline$55.4078$_inline;SPMamp;---;SPMamp;---157;SPMamp;358;SPMamp;51818;SPMamp;_inline$263.4490$_inline;SPMamp;_inline$56.6762$_inline;SPMamp;26.5;SPMamp;Yes158;SPMamp;359;SPMamp;51821;SPMamp;_inline$261.3115$_inline;SPMamp;_inline$53.3110$_inline;SPMamp;18.9;SPMamp;Yes159;SPMamp;360;SPMamp;51816;SPMamp;_inline$264.3484$_inline;SPMamp;_inline$54.5390$_inline;SPMamp;21.6;SPMamp;Yes159;SPMamp;362;SPMamp;51999;SPMamp;_inline$264.3484$_inline;SPMamp;_inline$54.5390$_inline;SPMamp;27.9;SPMamp;No74;SPMamp;363;SPMamp;51989;SPMamp;_inline$232.7451$_inline;SPMamp;_inline$0.0123$_inline;SPMamp;30.1;SPMamp;No155;SPMamp;366;SPMamp;52017;SPMamp;_inline$262.4414$_inline;SPMamp;_inline$58.8061$_inline;SPMamp;18.4;SPMamp;No156;SPMamp;367;SPMamp;51997;SPMamp;_inline$260.1872$_inline;SPMamp;_inline$55.4078$_inline;SPMamp;51.2;SPMamp;No171;SPMamp;382;SPMamp;---;SPMamp;_inline$349.2559$_inline;SPMamp;_inline$0.0289$_inline;SPMamp;---;SPMamp;---172;SPMamp;383;SPMamp;51818;SPMamp;_inline$351.2021$_inline;SPMamp;_inline$0.1141$_inline;SPMamp;28.3;SPMamp;Yes173;SPMamp;384;SPMamp;51821;SPMamp;_inline$353.2949$_inline;SPMamp;_inline$-0.0398$_inline;SPMamp;25.6;SPMamp;Yes174;SPMamp;385;SPMamp;51877;SPMamp;_inline$355.3896$_inline;SPMamp;_inline$0.0444$_inline;SPMamp;52.4;SPMamp;No175;SPMamp;386;SPMamp;51788;SPMamp;_inline$357.6322$_inline;SPMamp;_inline$0.0540$_inline;SPMamp;16.6;SPMamp;No176;SPMamp;387;SPMamp;51791;SPMamp;_inline$359.8243$_inline;SPMamp;_inline$0.0243$_inline;SPMamp;35.3;SPMamp;Yes177;SPMamp;388;SPMamp;51793;SPMamp;_inline$1.8246$_inline;SPMamp;_inline$-0.0050$_inline;SPMamp;18.4;SPMamp;Yes178;SPMamp;389;SPMamp;51795;SPMamp;_inline$3.5598$_inline;SPMamp;_inline$-0.0248$_inline;SPMamp;26.3;SPMamp;No179;SPMamp;390;SPMamp;51900;SPMamp;_inline$5.2229$_inline;SPMamp;_inline$-0.0332$_inline;SPMamp;53.3;SPMamp;Yes180;SPMamp;391;SPMamp;51782;SPMamp;_inline$6.9964$_inline;SPMamp;_inline$0.0453$_inline;SPMamp;18.7;SPMamp;No181;SPMamp;392;SPMamp;51793;SPMamp;_inline$8.8956$_inline;SPMamp;_inline$-0.0021$_inline;SPMamp;26.9;SPMamp;Yes182;SPMamp;393;SPMamp;51794;SPMamp;_inline$10.8188$_inline;SPMamp;_inline$0.0369$_inline;SPMamp;23.6;SPMamp;Yes183;SPMamp;394;SPMamp;51876;SPMamp;_inline$12.7276$_inline;SPMamp;_inline$-0.0330$_inline;SPMamp;38.7;SPMamp;Yes184;SPMamp;395;SPMamp;51783;SPMamp;_inline$14.6091$_inline;SPMamp;_inline$0.0160$_inline;SPMamp;22.3;SPMamp;No185;SPMamp;396;SPMamp;51816;SPMamp;_inline$16.4703$_inline;SPMamp;_inline$-0.0038$_inline;SPMamp;30.0;SPMamp;Yes186;SPMamp;397;SPMamp;51794;SPMamp;_inline$18.2698$_inline;SPMamp;_inline$0.0185$_inline;SPMamp;29.0;SPMamp;Yes187;SPMamp;398;SPMamp;51789;SPMamp;_inline$19.8354$_inline;SPMamp;_inline$0.0022$_inline;SPMamp;26.4;SPMamp;Yes188;SPMamp;399;SPMamp;51817;SPMamp;_inline$21.6700$_inline;SPMamp;_inline$0.0376$_inline;SPMamp;28.3;SPMamp;Yes189;SPMamp;400;SPMamp;51820;SPMamp;_inline$23.6367$_inline;SPMamp;_inline$0.0915$_inline;SPMamp;24.9;SPMamp;Yes190;SPMamp;401;SPMamp;51788;SPMamp;_inline$25.8247$_inline;SPMamp;_inline$-0.0208$_inline;SPMamp;23.2;SPMamp;No191;SPMamp;402;SPMamp;51793;SPMamp;_inline$27.9064$_inline;SPMamp;_inline$0.0018$_inline;SPMamp;28.6;SPMamp;Yes192;SPMamp;403;SPMamp;51871;SPMamp;_inline$29.8199$_inline;SPMamp;_inline$0.0102$_inline;SPMamp;24.8;SPMamp;Yes193;SPMamp;404;SPMamp;51812;SPMamp;_inline$31.6460$_inline;SPMamp;_inline$-0.0352$_inline;SPMamp;24.8;SPMamp;Yes194;SPMamp;405;SPMamp;51816;SPMamp;_inline$33.6829$_inline;SPMamp;_inline$-0.0329$_inline;SPMamp;20.2;SPMamp;Yes195;SPMamp;406;SPMamp;51817;SPMamp;_inline$35.8830$_inline;SPMamp;_inline$0.1250$_inline;SPMamp;30.4;SPMamp;Yes196;SPMamp;407;SPMamp;51820;SPMamp;_inline$37.8460$_inline;SPMamp;_inline$-0.0594$_inline;SPMamp;30.4;SPMamp;Yes197;SPMamp;408;SPMamp;51821;SPMamp;_inline$39.8224$_inline;SPMamp;_inline$0.0369$_inline;SPMamp;26.4;SPMamp;Yes198;SPMamp;409;SPMamp;51871;SPMamp;_inline$41.9984$_inline;SPMamp;_inline$0.0040$_inline;SPMamp;33.5;SPMamp;Yes199;SPMamp;410;SPMamp;51816;SPMamp;_inline$43.8616$_inline;SPMamp;_inline$-0.0170$_inline;SPMamp;24.0;SPMamp;Yes200;SPMamp;411;SPMamp;51817;SPMamp;_inline$45.7871$_inline;SPMamp;_inline$-0.0168$_inline;SPMamp;26.3;SPMamp;Yes201;SPMamp;412;SPMamp;51931;SPMamp;_inline$47.7341$_inline;SPMamp;_inline$0.0035$_inline;SPMamp;35.7;SPMamp;Yes202;SPMamp;413;SPMamp;51929;SPMamp;_inline$49.6868$_inline;SPMamp;_inline$0.0153$_inline;SPMamp;33.2;SPMamp;Yes203;SPMamp;414;SPMamp;51869;SPMamp;_inline$51.6314$_inline;SPMamp;_inline$-0.0118$_inline;SPMamp;39.7;SPMamp;Yes204;SPMamp;415;SPMamp;51810;SPMamp;_inline$53.5228$_inline;SPMamp;_inline$0.0307$_inline;SPMamp;25.7;SPMamp;No205;SPMamp;416;SPMamp;51811;SPMamp;_inline$55.4916$_inline;SPMamp;_inline$0.0138$_inline;SPMamp;38.6;SPMamp;Yesdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=766 HEIGHT=401 ALIGN=BOTTOM ALT="deluxetable1612" SRC="img196.gif">|; 
$key = q/{deluxetable}lccnormalsizetablecaptionExtinctionTermsandSecondOrderExtinctionCoefficientslabeltbl-ctermstablewidth0pttableheadcolheadFilter;SPMamp;colhead_inline$k$_inline;SPMamp;colhead_inline$c$_inlinestartdata_inline$u$_inline;SPMamp;_inline$0.55pm0.10$_inline;SPMamp;_inline$-0.021pm0.003$_inline_inline$g$_inline;SPMamp;_inline$0.15pm0.05$_inline;SPMamp;_inline$-0.016pm0.003$_inline_inline$r$_inline;SPMamp;_inline$0.10pm0.04$_inline;SPMamp;_inline$-0.004pm0.003$_inline_inline$i$_inline;SPMamp;_inline$0.08pm0.02$_inline;SPMamp;_inline$+0.006pm0.003$_inline_inline$z$_inline;SPMamp;_inline$0.06pm0.02$_inline;SPMamp;_inline$+0.003pm0.003$_inlinedata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=786 HEIGHT=481 ALIGN=BOTTOM ALT="deluxetable2330" SRC="img216.gif">|; 
$key = q/{deluxetable}lltabletypesizefootnotesizetablewidth0pttablecolumns2tablecaptionSDSSEDRDataQualitySummarylabeltbl-performancetableheadcolheadParameters;SPMamp;colheadPerformancestartdatacutinheadImagingPSF-FWHM;SPMamp;1.2-2.3arcsec95%completenesslimitforpointsource;SPMamp;_inline$u^*$_inline:22.0;_inline$g^*$_inline:22.2;_inline$r^*$_inline:22.2;_inline$i^*$_inline:21.3;_inline$z^*$_inline:20.5SkyCoveragewithinSurveyArea;SPMamp;98%(omittingareasaroundbrightstars)PhotometricCalibrationErrorsforPointSources;SPMamp;_inline$u^*$_inline:5%;_inline$g^*$_inline:3%;_inline$r^*$_inline:3%;_inline$i^*$_inline:3%;_inline$z^*$_inline:5%Star-GalaxySeparation;SPMamp;95%correctat21magnitudein_inline$r^*$_inlineAstrometricerrors;SPMamp;Absolute:_inline$;SPMlt;100$_inlinemas;Relative_inline$;SPMlt;50$_inlinemas;SPMamp;(bothrmspercoordinate)cutinheadSpectroscopyLimitingmagnitude;SPMamp;_inline$SN=4.5$_inlinepixelat_inline$lambdaf_lambda=10^-13$_inlineergscm_inline$^2$_inlinesecErroringalaxyredshifts;SPMamp;_inline$Deltaz=0.0001$_inline(_inline$approx$_inline30~km~s_inline$^-1$_inline)Errorinquasarredshifts;SPMamp;_inline$Deltaz=0.001$_inlineSuccessrate,redshiftsforgalaxies;SPMamp;_inline$;SPMgt;99$_inline%Successrate,redshiftsforquasars;SPMamp;98%data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=766 HEIGHT=401 ALIGN=BOTTOM ALT="deluxetable1572" SRC="img194.gif">|; 
$key = q/{_inline}$r^ast=17.6${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3505" SRC="img177.gif">|; 
$key = q/{_inline}$times${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=9 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline2843" SRC="img14.gif">|; 
$key = q/{_inline}$sim${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=5 ALIGN=BOTTOM ALT="tex2html_wrap_inline3371" SRC="img141.gif">|; 
$key = q/{deluxetable}rccccc|ccc|cctabletypesizescriptsizetablecaptionPipelineVersionsusedforEarlyDataReleaselabeltbl-pipelineversionstablewidth0pttableheadcolheadRun;SPMamp;colheadttastromtablenotemarka;SPMamp;colheadttpsptablenotemarkb;SPMamp;colheadttframestablenotemarkc;SPMamp;colheadttmtpipetablenotemarkd;SPMamp;colheadttnfcalibtablenotemarke;SPMamp;colheadttresolvetablenotemarkf;SPMamp;colheadtttargettablenotemarkg;SPMamp;colheadttplatetablenotemarkh;SPMamp;colheadttspectro2dtablenotemarki;SPMamp;colheadttspectro1dtablenotemarkjstartdata94;SPMamp;v3.3;SPMamp;v5.2.21;SPMamp;v5.2.21;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.7;SPMamp;v2.7;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.2125;SPMamp;v3.3;SPMamp;v5.2.21;SPMamp;v5.2.21;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.7;SPMamp;v2.7;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.2752;SPMamp;v3.3;SPMamp;v5.2.6;SPMamp;v5.2.6;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.2a;SPMamp;v2.2a;SPMamp;v2.3;SPMamp;v4.6.2;SPMamp;v5.3.2756;SPMamp;v3.2;SPMamp;v5.2.6;SPMamp;v5.2.6;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.2a;SPMamp;v2.2a;SPMamp;v2.3;SPMamp;v4.6.2;SPMamp;v5.3.21336;SPMamp;v3.3;SPMamp;v5.2.12;SPMamp;v5.2.12;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.5;SPMamp;v2.5;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.21339;SPMamp;v3.3;SPMamp;v5.2.12;SPMamp;v5.2.12;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.5;SPMamp;v2.5;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.21356;SPMamp;v3.3;SPMamp;v5.2.12;SPMamp;v5.2.12;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.5;SPMamp;v2.5;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.21359;SPMamp;v3.3;SPMamp;v5.2.10;SPMamp;v5.2.10;SPMamp;v7.2;SPMamp;v1.7.8;SPMamp;v2.5;SPMamp;v2.5;SPMamp;v2.6;SPMamp;v4.6.2;SPMamp;v5.3.2datatablenotetextattastromprovidestheastrometriccalibrationforimagingdata.tablenotetextbThepostagestamppipeline(ttpsp)characterizesthepointspreadfunctionandskylevelduringanimagingrun.tablenotetextcttframesfindsandmeasuresobjectsinimagingdata.tablenotetextdttmtpipefindsandmeasuresobjectsindatafromthePhotometricTelescope.tablenotetexteFinalPhotometricCalibrationttnfcalibmatchesobjectsfromttframesandttmtpipetocalibrateimagingdata.tablenotetextfttresolvechoosesamongmultipledetectionsofobjectsinoverlapareastodefinetheprimarysetofdetectedobjects.tablenotetextgtttargetselectsprimaryobjectsforspectroscopicobservation.tablenotetexthttplatedefineslocationsofholesinanaluminumplugplateforspectroscopictargets.tablenotetextittspectro2dextractsandflux-calibratesspectrafromthefullspectroscopicframes.tablenotetextjttspectro1didentifiesandmeasurestheextractedspectra.{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=786 HEIGHT=481 ALIGN=BOTTOM ALT="deluxetable2219" SRC="img212.gif">|; 
$key = q/{_inline}$sigmaapprox0.03${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3041" SRC="img62.gif">|; 
$key = q/{_inline}$r^*;SPMlt;17.7${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3129" SRC="img88.gif">|; 
$key = q/{_inline}$1,sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline3069" SRC="img70.gif">|; 
$key = q/{_inline}$sim6000${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=51 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3533" SRC="img182.gif">|; 
$key = q/{_inline}$pm2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline3307" SRC="img131.gif">|; 
$key = q/{deluxetable}llltabletypesizetinytablecaptionSpectroscopicParameters:LinesandRedshiftslabeltbl-specinfotablewidth0pttablecolumns4tableheadcolheadName;SPMamp;colheadType;SPMamp;colheadDescriptionstartdatahlinevspace-6ptmulticolumn3cnormalsizeClassbfSpecLine:(inobservedframe)multicolumn3cIdentifiedSpectroscopicLines[4pt]hlinespecline_ID;SPMamp;int64;SPMamp;UniqueIDwave;SPMamp;float32;SPMamp;Linecenter(AA)waveErr;SPMamp;float32;SPMamp;Errorinlinecenter(AA)waveMin;SPMamp;float32;SPMamp;Minimumwavelengthoflineinfluence(AA)waveMax;SPMamp;float32;SPMamp;Maximumwavelengthoflineinfluence(AA)sigma;SPMamp;float32;SPMamp;Sigmaoffittedgaussian(AA)sigmaErr;SPMamp;float32;SPMamp;Errorofsigma(AA)sigmaMin;SPMamp;float32;SPMamp;Minimumsigmaallowedbyfit(AA)sigmaMax;SPMamp;float32;SPMamp;Maximumsigmaallowedbyfit(AA)height;SPMamp;float32;SPMamp;Heightofgaussian(_inline$10^-17$_inlineergscm_inline$^2$_inlineAA)heightErr;SPMamp;float32;SPMamp;Errorinheight(_inline$10^-17$_inlineergscm_inline$^2$_inlineAA)continuum;SPMamp;float32;SPMamp;Continuumvalueatthispixel(_inline$10^-17$_inlineergscm_inline$^2$_inlineAA)ew;SPMamp;float32;SPMamp;Equivalentwidth(AA)ewErr;SPMamp;float32;SPMamp;Errorinequivalentwidth(AA)ewMin;SPMamp;float32;SPMamp;Minimumequivalentwidthallowedforlinedetection(AA)specIndex;SPMamp;float32;SPMamp;Spectralindex(notused)nSigma;SPMamp;float32;SPMamp;Significanceoflinenumberofsigma(notused)chisq;SPMamp;float32;SPMamp;_inline$chi^2$_inlineoffitnu;SPMamp;int16;SPMamp;NumberofdegreesoffreedomrestWave;SPMamp;float32;SPMamp;Linerestwavelength(AA)weight;SPMamp;float32;SPMamp;Weightoflineinredshiftdeterminationz;SPMamp;float32;SPMamp;Redshiftofline(heliocentric)zErr;SPMamp;float32;SPMamp;ErrorinredshiftlineMask;SPMamp;uint32;SPMamp;Linemask(notused)category;SPMamp;int16;SPMamp;Category:Linefound(0)ormeasured(1)specobj;spec;SPMamp;OneAssoc(SpecObj);SPMamp;Linktospectrumobjectspeclinename;linename;name;SPMamp;OneAssoc(SpecLineName);SPMamp;Linktolinename[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfSpecLineName:multicolumn3cNamesofspectrallineshlinelineID;SPMamp;int32;SPMamp;LineIDrestWave;SPMamp;float32;SPMamp;Linerestwavelength(AA)name;SPMamp;char[16];SPMamp;Linename[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfSpecLineIndex:(inrestframe)multicolumn3cSpectralIndiceshlinespeclineindex_ID;SPMamp;int64;SPMamp;UniqueIDname;SPMamp;char[16];SPMamp;Nameew;SPMamp;float32;SPMamp;Equivalentwidth(AA)orfluxratioewErr;SPMamp;float32;SPMamp;Equivalentwidtherror(AA)mag;SPMamp;float32;SPMamp;Magnitude(2.5log(EW))ofthelineindexmagErr;SPMamp;float32;SPMamp;MagnitudeerrorwaveMin;SPMamp;float32;SPMamp;MinimumrestwavelengthusedtocalculatetheindexwaveMax;SPMamp;float32;SPMamp;Maximumrestwavelengthusedtocalculatetheindexz;SPMamp;float32;SPMamp;Redshiftsn;SPMamp;float32;SPMamp;Signal-to-noiseratiospecobj;spec;SPMamp;OneAssoc(SpecObj);SPMamp;Linktospectrumobject[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfCrossCorrelationRedshift:multicolumn3cResultsofcross-correlationredshiftmeasurementhlinecrosscorrelationredshift_ID;xcz_ID;SPMamp;int64;SPMamp;UniqueIDtempNo;temp_no;SPMamp;int16;SPMamp;TemplatenumberpeakNo;peak_no;SPMamp;int16;SPMamp;Peaknumbershift;SPMamp;float32;SPMamp;Numberofpixelsbetweenobjectandtemplatez;SPMamp;float32;SPMamp;RedshiftfromthispeakzErr;z_err;SPMamp;float32;SPMamp;Errorinredshiftr;SPMamp;float32;SPMamp;Tonry&DavisrzConf;con;conf;z_conf;SPMamp;float32;SPMamp;Confidenceheight;SPMamp;float32;SPMamp;HeightofCCFPeakwidth;SPMamp;float32;SPMamp;WidthofCCFPeakwidthErr;width_err;SPMamp;float32;SPMamp;ErrorinCCFwidthdelta;SPMamp;float32;SPMamp;ErrorinCCFPeakrms;SPMamp;float32;SPMamp;RMSofCCFspecobj;spec;SPMamp;OneAssoc(SpecObj);SPMamp;Linktospectrumobject[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfEmissionRedshift:multicolumn3cResultsofemissionlineredshiftmeasurement[4pt]hlineemissionredshift_ID;emz_ID;SPMamp;int64;SPMamp;UniqueIDz;SPMamp;float32;SPMamp;RedshiftzErr;SPMamp;float32;SPMamp;ErrorinredshiftzConf;SPMamp;float32;SPMamp;ConfidenceinredshiftnFit;SPMamp;int32;SPMamp;NumberofmatchedlineswtFit;fitWeight;SPMamp;float32;SPMamp;Weightoffitspecobj;spec;SPMamp;OneAssoc(SpecObj);SPMamp;Linktospectrumobjectdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=613 HEIGHT=340 ALIGN=BOTTOM ALT="deluxetable1943" SRC="img204.gif">|; 
$key = q/{_inline}$4,sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline3437" SRC="img158.gif">|; 
$key = q/{figure}plotonePSFmosaic-000752-0227.pslabelfig-psfmosaic{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=735 HEIGHT=384 ALIGN=BOTTOM ALT="figure2724" SRC="img231.gif">|; 
$key = q/{_inline}$19;SPMlt;r^*;SPMlt;20${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=95 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3255" SRC="img122.gif">|; 
$key = q/{_inline}$4,r_e${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3139" SRC="img95.gif">|; 
$key = q/{_inline}$zge2.2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3425" SRC="img154.gif">|; 
$key = q/{_inline}$u'_rminst${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=31 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3219" SRC="img117.gif">|; 
$key = q/{_inline}$,rlapraise5pthbox$char'076$mathchar;SPMquot;7218,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline2797" SRC="img2.gif">|; 
$key = q/{_inline}$8,r_e${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3133" SRC="img91.gif">|; 
$key = q/{_inline}$eta${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=9 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2919" SRC="img34.gif">|; 
$key = q/{figure}plotonefig_WedgeEqQso_v2.pslabelfig-WedgeEqQso{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=706 HEIGHT=302 ALIGN=BOTTOM ALT="figure2779" SRC="img244.gif">|; 
$key = q/{deluxetable}llltabletypesizetinytablecaptionImagingRun,Chunk,andSegmentClasseslabeltbl-administrative-runchunksegmenttablewidth0pttablecolumns3tableheadcolheadName;SPMamp;colheadType;SPMamp;colheadDescriptionstartdatahlinevspace-6ptmulticolumn3cnormalsizeClassbfRun:multicolumn3cOnecontinuousphotometricobservationhlinerun;runNumber;SPMamp;int32;SPMamp;RunnumberskyNodes;SPMamp;int64[];SPMamp;Level5HTMnodesofthisrunchunk;Chunk;SPMamp;ManyAssoc(sxChunk);SPMamp;Linktothechunksthisrunispartofsegment;Segment;SPMamp;ManyAssoc(sxSegment);SPMamp;Linktothesegmentsofthisrun[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfChunk:multicolumn3cCompletelyobservedpairofstripshlinechunkNumber;SPMamp;int16;SPMamp;ChunknumberstartMu;SPMamp;int32;SPMamp;StartingcoordinateinGreatCirclecoordinatesMu;SPMamp;int32;SPMamp;EndingcoordinateinGreatCirclecoordinatesstripe;SPMamp;int32;SPMamp;StripenumberexportVersion;SPMamp;char[32];SPMamp;Exportversionsegment;Segment;SPMamp;ManyAssoc(sxSegment);SPMamp;Linktoallsegmentsofthischunk[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfSegment:multicolumn3cAsinglecameracolumnwithinachunkhlinesegment_ID;id;segID;SPMamp;int64;SPMamp;Uniquesegmentidentifierrun;SPMamp;int32;SPMamp;RunnumberofthissegmentcamCol;SPMamp;int32;SPMamp;Cameracolumnnumber(1-6)rerun;SPMamp;int32;SPMamp;Rerunnumberfield0;SPMamp;int32;SPMamp;StartingfieldnumbernFields;SPMamp;int32;SPMamp;Numberoffieldsinsegmentdscale;SPMamp;int32;SPMamp;Scalingforbiasstrip;SPMamp;int16;SPMamp;Strip(NorS)status;SPMamp;int16;SPMamp;Status:primary,secondaryorbadresolved;SPMamp;int16;SPMamp;Resolvedflag(yesno)exported;SPMamp;int16;SPMamp;Exportedflag(yesno)families;SPMamp;int16;SPMamp;Familiesidentifiedflag(yesno)loadMJD;SPMamp;float64;SPMamp;DateTimeatloadingofdatabaseequinox;SPMamp;float64;SPMamp;GreatCircleEquinoxnode;SPMamp;float64;SPMamp;GreatCircleAscingNodeincl;SPMamp;float64;SPMamp;GreatCircleInclinationcObs;c_obs;SPMamp;float64;SPMamp;CCDClockratetracking;SPMamp;float64;SPMamp;TrackingRateraMin;ramin;SPMamp;float64;SPMamp;LowestJ2000RA(degrees)raMax;ramax;SPMamp;float64;SPMamp;HighestJ2000RA(degrees)decMin;decmin;SPMamp;float64;SPMamp;LowestJ2000Dec(degrees)decMax;decmax;SPMamp;float64;SPMamp;HighestJ2000Dec(degrees)lMin;lmin;SPMamp;float64;SPMamp;LowestGalacticlongitude(degrees)lMax;lmax;SPMamp;float64;SPMamp;HighestGalacticlongitude(degrees)bMin;bmin;SPMamp;float64;SPMamp;LowestGalacticlatitude(degrees)bMax;bmax;SPMamp;float64;SPMamp;HighestGalacticlatitude(degrees)lambdaMin;lambdamin;SPMamp;float64;SPMamp;Lowestsurvey_inline$lambda$_inline(degrees)lambdaMax;lambdamax;SPMamp;float64;SPMamp;Highestsurvey_inline$lambda$_inline(degrees)etaMin;etamin;SPMamp;float64;SPMamp;Lowestsurvey_inline$eta$_inline(degrees)etaMax;etamax;SPMamp;float64;SPMamp;Highestsurvey_inline$eta$_inline(degrees)photoId;photo_id;SPMamp;char[32];SPMamp;PhotoIDtagphotoVersion;phot_ver;SPMamp;char[32];SPMamp;PhotoversiontargetAstroId;tast_id;SPMamp;char[32];SPMamp;AstrometricpipelineusedfortargettargetAstroVersion;tast_ver;SPMamp;char[32];SPMamp;AstrometricpipelineversionusedfortargetselectionexportAstroId;eastr_id;SPMamp;char[32];SPMamp;AstrometriccalibrationusedforexporttoSX.exportAstroVersion;eastr_ver;SPMamp;char[32];SPMamp;AstrometricpipelineversionusedforexporttoSX.targetFCalibId;tfcal_id;SPMamp;char[32];SPMamp;Photometriccalibrationusedfortargetselection.targetFCalibVersion;tfcal_ver;SPMamp;char[32];SPMamp;FCALIBpipelineversionusedfortargetselectionexportFCalibId;efcal_id;SPMamp;char[32];SPMamp;PhotometriccalibrationusedforexporttoSX.exportFCalibVersion;efcal_ver;SPMamp;char[32];SPMamp;FCALIBpipelineversionusedforexporttoSX.sxLoaderVersion;;SPMamp;char[32];SPMamp;VersionofSXLoaderusedtoloadthissegmentindentloaderVersion;load_ver;SPMamp;;SPMamp;objectSource;obj_src;SPMamp;char[32];SPMamp;ObjectSourcetargetSource;targ_src;SPMamp;char[32];SPMamp;TargetSourcetargetVersion;SPMamp;char[32];SPMamp;TargetversionskyMask_;skyMask;SPMamp;uint32[];SPMamp;BitMaskencodedHTMnodescoveredbythissegmentskyMaskLength_;skyMaskLength;SPMamp;uint32;SPMamp;LengthofBitMaskfield;Field;SPMamp;ManyAssoc(sxField);SPMamp;Linktofieldsinthissegmentchunk;Chunk;SPMamp;OneAssoc(sxChunk);SPMamp;Linktothechunkthissegmentbelongsto[4pt]data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=773 HEIGHT=699 ALIGN=BOTTOM ALT="deluxetable2040" SRC="img207.gif">|; 
$key = q/{_inline}$i^*=19.9${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2969" SRC="img53.gif">|; 
$key = q/{_inline}$A_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3149" SRC="img98.gif">|; 
$key = q/{_inline}$phi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=9 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3177" SRC="img108.gif">|; 
$key = q/{_inline}$i^*;SPMlt;16.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3439" SRC="img159.gif">|; 
$key = q/{_inline}$(SN)^2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2833" SRC="img12.gif">|; 
$key = q/{_inline}$g,r${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2853" SRC="img17.gif">|; 
$key = q/{_inline}$(g^*-r^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3291" SRC="img126.gif">|; 
$key = q/{_inline}$4times4${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=38 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2839" SRC="img13.gif">|; 
$key = q/{_inline}$g^*=20.2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2831" SRC="img11.gif">|; 
$key = q/{_inline}$arcsec${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline3039" SRC="img61.gif">|; 
$key = q/{_inline}$Lambda=0.7${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=748 HEIGHT=338 ALIGN=BOTTOM ALT="tex2html_wrap_inline9999" SRC="img239.gif">|; 
$key = q/{_inline}$langleXrangle=1.3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3253" SRC="img121.gif">|; 
$key = q/{_inline}$lambda=0arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=47 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2923" SRC="img36.gif">|; 
$key = q/{_inline}$F_P${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3109" SRC="img81.gif">|; 
$key = q/{_inline}$f_0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3075" SRC="img72.gif">|; 
$key = q/{_inline}$10^6${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2803" SRC="img4.gif">|; 
$key = q/{_inline}$delta_2000=32.5arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=95 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2929" SRC="img38.gif">|; 
$key = q/{deluxetable}cccccccctablecaptionEarlyDataReleaseImagingDatalabeltbl-edr-imagingtablewidth0pttablecolumns8tableheadcolheadRun;SPMamp;colheadStrip;SPMamp;colheadNetArea(deg_inline$^2$_inline);SPMamp;colheadLocation;SPMamp;colhead_inline$lambda$_inline;SPMamp;colhead_inline$eta$_inline;SPMamp;colheadBeginField;SPMamp;colheadEndFieldstartdatacutinheadSeptember1998:SouthEquatorialStripe94;SPMamp;82N;SPMamp;83;SPMamp;_inline$alpha=351arcdeg$_inline--_inline$56arcdeg$_inline;SPMamp;_inline$[166^circ,-129^circ]$_inlinetablenotemarka;SPMamp;_inline$-32.5^circ$_inline;SPMamp;104;SPMamp;544125;SPMamp;82S;SPMamp;83;SPMamp;_inline$delta=0^circ$_inline;SPMamp;;SPMamp;;SPMamp;11;SPMamp;451cutinheadMarch1999:NorthEquatorialStripe752;SPMamp;10S;SPMamp;114;SPMamp;_inline$alpha=145arcdeg$_inline--_inline$236arcdeg$_inline;SPMamp;_inline$[-40^circ,51^circ$_inline];SPMamp;_inline$-32.5^circ$_inline;SPMamp;11;SPMamp;617756;SPMamp;10N;SPMamp;114;SPMamp;_inline$delta=0^circ$_inline;SPMamp;;SPMamp;;SPMamp;196;SPMamp;802cutinheadApril2000:SIRTFFirstLookSurvey1336;SPMamp;42N;SPMamp;16;SPMamp;_inline$alpha$_inline:_inline$257arcdeg$_inline,_inline$delta$_inline:_inline$59arcdeg$_inlinetablenotemarkb;SPMamp;[_inline$23^circ,36^circ$_inline];SPMamp;_inline$47.5^circ$_inline;SPMamp;11;SPMamp;951339;SPMamp;42S;SPMamp;16;SPMamp;;SPMamp;;SPMamp;;SPMamp;11;SPMamp;951356;SPMamp;43N;SPMamp;17;SPMamp;_inline$alpha$_inline:_inline$261arcdeg$_inline,_inline$delta$_inline:_inline$60arcdeg$_inline;SPMamp;_inline$[22.8^circ,35.8^circ]$_inline;SPMamp;_inline$50^circ$_inline;SPMamp;20;SPMamp;1131359;SPMamp;43S;SPMamp;19;SPMamp;;SPMamp;;SPMamp;;SPMamp;19;SPMamp;113Total;SPMamp;;SPMamp;462datatablenotetextaThe_inline$lambda$_inlinecoordinatesat_inline$180^circequiv-180^circ$_inlinetablenotetextbCenteroftheFirstLookarea{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=766 HEIGHT=401 ALIGN=BOTTOM ALT="deluxetable1586" SRC="img195.gif">|; 
$key = q/{_inline}$10'times13.5'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3031" SRC="img59.gif">|; 
$key = q/{_inline}$g^*r^*i^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3283" SRC="img125.gif">|; 
$key = q/{_inline}$2.5arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=27 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2935" SRC="img39.gif">|; 
$key = q/{_inline}$lambda^-0.2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline3341" SRC="img135.gif">|; 
$key = q/{_inline}$;SPMlt;2%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3035" SRC="img60.gif">|; 
$key = q/{_inline}$N_P${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3103" SRC="img79.gif">|; 
$key = q/{_inline}$2,r_P${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=28 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3111" SRC="img82.gif">|; 
$key = q/{_inline}$r^*=15.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3367" SRC="img140.gif">|; 
$key = q/{_inline}$r^*=17.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3049" SRC="img65.gif">|; 
$key = q/{_inline}$Delta_ROW=row-ttCRPIX2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=178 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3029" SRC="img58.gif">|; 
$key = q/{_inline}$200sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=35 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3047" SRC="img64.gif">|; 
$key = q/{_inline}$10,f_0b${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=43 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3081" SRC="img73.gif">|; 
$key = q/{_inline}$zapprox0.4${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3387" SRC="img144.gif">|; 
$key = q/{deluxetable}rrrrtablecaptionRadiiforprofMeanandprofErrMeasurementslabeltbl-radiitablewidth0pttablecolumns4tableheadcolheadaperture;SPMamp;colheadradius(pixels);SPMamp;colheadradius(arcsec);SPMamp;colheadarea(pixels)startdata1;SPMamp;0.56;SPMamp;0.23;SPMamp;12;SPMamp;1.69;SPMamp;0.68;SPMamp;93;SPMamp;2.58;SPMamp;1.03;SPMamp;214;SPMamp;4.41;SPMamp;1.76;SPMamp;615;SPMamp;7.51;SPMamp;3.00;SPMamp;1776;SPMamp;11.58;SPMamp;4.63;SPMamp;4217;SPMamp;18.58;SPMamp;7.43;SPMamp;10858;SPMamp;28.55;SPMamp;11.42;SPMamp;25619;SPMamp;45.50;SPMamp;18.20;SPMamp;650510;SPMamp;70.15;SPMamp;28.20;SPMamp;1561911;SPMamp;110.50;SPMamp;44.21;SPMamp;3838112;SPMamp;172.50;SPMamp;69.00;SPMamp;9347513;SPMamp;269.50;SPMamp;107.81;SPMamp;22820714;SPMamp;420.50;SPMamp;168.20;SPMamp;55552515;SPMamp;657.50;SPMamp;263.00;SPMamp;1358149data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=643 HEIGHT=882 ALIGN=BOTTOM ALT="deluxetable1730" SRC="img199.gif">|; 
$key = q/{_inline}$ln^2(lambdalambda_eff)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=86 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2889" SRC="img25.gif">|; 
$key = q/{_inline}$u^*-g^*;SPMgt;1.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=100 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3463" SRC="img170.gif">|; 
$key = q/{figure}includegraphics[angle=-90,scale=0.75]fig_edr-flow.pslabelfig_edr-flow.ps{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=735 HEIGHT=384 ALIGN=BOTTOM ALT="figure2703" SRC="img227.gif">|; 
$key = q/{_inline}$3,r_e${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3137" SRC="img94.gif">|; 
$key = q/{_inline}$g^*-r^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3301" SRC="img129.gif">|; 
$key = q/{_inline}$r^*_Petrosian=17.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=123 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3357" SRC="img139.gif">|; 
$key = q/{_inline}$f(ttexp_L)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3167" SRC="img103.gif">|; 
$key = q/{_inline}$7,r_e${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3131" SRC="img90.gif">|; 
$key = q/{_inline}$(g^*-r^*),(r^*-i^*),(i^*-z^*)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=209 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3433" SRC="img157.gif">|; 
$key = q/{_inline}$r^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline2863" SRC="img21.gif">|; 
$key = q/{_inline}$f_c(lambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3535" SRC="img183.gif">|; 
$key = q/{_inline}$mathcalR_P${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3087" SRC="img74.gif">|; 
$key = q/{_inline}$i^*;SPMlt;19.0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3451" SRC="img168.gif">|; 
$key = q/{_inline}$;SPMlt;5%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3119" SRC="img84.gif">|; 
$key = q/{_inline}$i^*-z^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=50 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3305" SRC="img130.gif">|; 
$key = q/{_inline}$r_P${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=15 ALIGN=MIDDLE ALT="tex2html_wrap_inline3097" SRC="img76.gif">|; 
$key = q/{_inline}$r^*approx17.7${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3117" SRC="img83.gif">|; 
$key = q/{deluxetable}llltabletypesizetinytablecaptionStatisticsClasslabeltbl-administrative-statisticstablewidth0pttablecolumns3tableheadcolheadName;SPMamp;colheadType;SPMamp;colheadDescriptionstartdatahlinevspace-6ptmulticolumn3cnormalsizeClassbfStatistics:multicolumn3cTotalnumberofchunks,runs,fields,objectsandsegmentshlinenChunk;SPMamp;int32;SPMamp;NumberofchunkobjectsnRun;SPMamp;int32;SPMamp;NumberofrunobjectsnSegment;SPMamp;int32;SPMamp;NumberofsegmentsnField;SPMamp;int32;SPMamp;NumberoffieldsnPhotoObj;SPMamp;int32;SPMamp;NumberofPhotoObjectsnPrimary;SPMamp;int32;SPMamp;NumberofPrimaryPhotoObjectsnSecondary;SPMamp;int32;SPMamp;NumberofSecondaryPhotoObjectsnFamily;SPMamp;int32;SPMamp;NumberofFamilyObjectsnStar;SPMamp;int32;SPMamp;NumberofobjectsclassifiedasstarsnGalaxy;SPMamp;int32;SPMamp;NumberofobectsclassifiedasgalaxiesnSky;SPMamp;int32;SPMamp;NumberofobjectsclassifiedasskynUnknown;SPMamp;int32;SPMamp;NumberofobjectsclassifiedasunknownnStarSec;SPMamp;int32;SPMamp;NumberofsecondaryobjectsclassifiedasstarnGalaxySec;SPMamp;int32;SPMamp;NumberofsecondaryobjectsclassifiedasgalaxynSkySec;SPMamp;int32;SPMamp;NumberofsecondaryobjectsclassifiedasskynUnknownSec;SPMamp;int32;SPMamp;NumberofsecondaryobjectsclassifiedasunknownnExternal;SPMamp;int32;SPMamp;NumberofexternalobjectsnPlate;SPMamp;int32;SPMamp;NumberofplatesnSpecObj;SPMamp;int32;SPMamp;NumberofspectranSpecLine;SPMamp;int32;SPMamp;NumberofspectrallinesnSpecLineIndex;SPMamp;int32;SPMamp;Numberofspectrallineindicesdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=613 HEIGHT=340 ALIGN=BOTTOM ALT="deluxetable2022" SRC="img206.gif">|; 
$key = q/{_inline}$mu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=10 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2949" SRC="img47.gif">|; 
$key = q/{_inline}$z^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3205" SRC="img112.gif">|; 
$key = q/{_inline}$z^*=20.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3061" SRC="img69.gif">|; 
$key = q/{_inline}$chi^2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3143" SRC="img97.gif">|; 
$key = q/{_inline}$r^*;SPMlt;18${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3141" SRC="img96.gif">|; 
$key = q/{_inline}$eta=0arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=47 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2925" SRC="img37.gif">|; 
$key = q/{deluxetable}lllltabletypesizetinytablecaptionImageParametersforObjectsfromExternalCatalogslabeltbl-externaltablewidth0pttablecolumns3tableheadcolheadName;SPMamp;colheadType;SPMamp;colheadDescriptionstartdatahlinevspace-6ptmulticolumn3cnormalsizeClassbfExternalCatalog:multicolumn3cExternalObject[4pt]hlinedelta;SPMamp;float32;SPMamp;Positiondifferencebetweencatalogand_inline$r$_inlinephotoobject(arcsec)match;SPMamp;int32;SPMamp;Matchtodifferentcatalogs;SPMamp;;SPMamp;USNO:1=matchtocatalogwithin30;SPMquot;;SPMamp;;SPMamp;FIRST:numberofmatchestocatalogwithin1.5;SPMquot;;SPMamp;;SPMamp;ROSAT:1=matchtocatalogwithin60;SPMquot;type;SPMamp;int16;SPMamp;Objectmatchtype;SPMamp;;SPMamp;ROSAT_MATCH=0;SPMamp;;SPMamp;FIRST_MATCH=1;SPMamp;;SPMamp;USNO_MATCH=2phototag;PhotoTag;obj;pobj;SPMamp;OneAssoc(PhotoTag);SPMamp;Linktophototagobject[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfFIRST:multicolumn3cSDSSobjectsthatmatchtoFIRSTobjectshavetheirmatchparametersstoredhere.multicolumn3cInheritseverythingfromExternalCatalog,plushas:hlinepeak;firstPeak;SPMamp;float32;SPMamp;Peakfirstradioflux(mJy)integr;int;firstInt;SPMamp;float32;SPMamp;Integratedfirstradioflux(mJy)rms;firstRms;SPMamp;float32;SPMamp;rmserrorinflux(mJy)major;firstMajor;SPMamp;float32;SPMamp;Majoraxis(deconvolved)(arcsec)minor;firstMinor;SPMamp;float32;SPMamp;Minoraxis(deconvolved)(arcsec)pa;firstPa;SPMamp;float32;SPMamp;positionangle(eastofnorth)(degrees)id;firstId;SPMamp;int32;SPMamp;FIRSTcatalogidofonematchingsourcelambda;SPMamp;float64;SPMamp;Compositeradiosourcesurveylongitude(degrees)eta;SPMamp;float64;SPMamp;Compositeradiosourcesurveylatitude(degrees)[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfROSAT:multicolumn3cSDSSobjectsthatmatchtoRosatobjectshavetheirmatchparametersstoredhere.multicolumn3cInheritseverythingfromExternalCatalog,plushas:hlinecps;rosatCps;SPMamp;float32;SPMamp;integratedROSATcounts(countssec)hard1;rosatHr1;hr1;SPMamp;float32;SPMamp;ROSAThardnessratio1hard2;rosatHr2;hr2;SPMamp;float32;SPMamp;ROSAThardnessratio2extent;rosatExt;ext;SPMamp;float32;SPMamp;ROSATextentparameter(arcsec)exposure;rosatExposure;SPMamp;float32;SPMamp;ROSATexposuretime(seconds)posErr;rosatPosErr;poserr;SPMamp;float32;SPMamp;ErrorinROSATposition(arcsec)cpsErr;rosatCpsErr;cpserr;SPMamp;float32;SPMamp;ErrorinintegratedROSATcounts(countssec)hard1Err;rosatHr1Err;hr1Err;SPMamp;float32;SPMamp;ErrorinROSAThardnessratio1hard2Err;rosatHr2Err;hr2Err;SPMamp;float32;SPMamp;ErrorinROSAThardnessratio2extentLike;rosatExtLike;SPMamp;float32;SPMamp;ROSATextentparameterlikelihooddetectLike;rosatDetectLike;SPMamp;float32;SPMamp;ROSATdetectionlikelihood[4pt]hlinevspace-6ptmulticolumn3cnormalsizeClassbfUSNO:multicolumn3cSDSSobjectsthatmatchtoUSNOA2.0objectshavetheirmatchparametersstoredhere.multicolumn3cInheritseverythingfromExternalCatalog,plushas:hlinepropermotion;SPMamp;float32;SPMamp;Propermotionofobject(arcseccentury)angle;propermotionangle;SPMamp;float32;SPMamp;Directionofpropermotion(degrees(+NthroughE))blue;usnoBlue;SPMamp;float32;SPMamp;BluemagnitudeofmatchingUSNOobject(mag)red;usnoRed;SPMamp;float32;SPMamp;RedmagnitudeofmatchingUSNOobject(mag)data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=760 HEIGHT=998 ALIGN=BOTTOM ALT="deluxetable1824" SRC="img202.gif">|; 
$key = q/{deluxetable}llltabletypesizescriptsizetablecaptionProcessingflagsassociatedwithMeasuringObjectsinttframeslabeltbl-flagtablecommentsTheseflagsgetsetbothineachband,and,insomecases,fortheobjectasawhole.Amorethoroughdescriptionoftheflagsandtheirmeaningisavailableonourwebsites.tablewidth0pttablecolumns3tableheadcolheadName;SPMamp;colheadHexBit;SPMamp;colheadDescriptionstartdatattBRIGHT;SPMamp;0x2;SPMamp;Objectwasdetectedinfirst,``bright''object-finding;SPMamp;;SPMamp;step;generallybrighterthan_inline$r^*=17.5$_inlinettSUBTRACTED;SPMamp;0x100000;SPMamp;ThisttBRIGHTobjecthaditswingssubtractedfromtheframettBINNED1;SPMamp;0x10000000;SPMamp;Thisobjectwasdetectedinthe_inline$1times1$_inline,unbinnedimage.ttBINNED2;SPMamp;0x20000000;SPMamp;Thisobjectwasdetectedinthe_inline$2times2$_inlinebinnedimage,;SPMamp;;SPMamp;afterunbinneddetectionsarereplacedbybackground.ttBINNED4;SPMamp;0x40000000;SPMamp;Thisobjectwasdetectedinthe_inline$4times4$_inlinebinnedimage.ttEDGE;SPMamp;0x4;SPMamp;ObjectwastooclosetoedgeofframettLOCAL_EDGE;SPMamp;0x8000000000;SPMamp;Centerinatleastonebandistooclosetoanedge.ttSATUR;SPMamp;0x40000;SPMamp;TheobjectcontainsoneormoresaturatedpixelsttSATUR_CENTER;SPMamp;0x80000000000;SPMamp;Theobjectcenterisclosetoatleastonesaturatedpixel.ttBLENDED;SPMamp;0x8;SPMamp;Objecthadmultiplepeaksdetectedwithinit;was;SPMamp;;SPMamp;thusacandidatetobeadeblingparentttNODEBLEND;SPMamp;0x40;SPMamp;Nodeblingwasattemptedonthisobject,eventhoughitisttBLENDED.ttDEBLEND_TOO_MANY_PEAKS;SPMamp;0x800;SPMamp;Thereweremorethan25peaksinthisobjectto;SPMamp;;SPMamp;debl;debledbrightest25ttDEBLEND_PRUNED;SPMamp;0x4000000;SPMamp;Atleastonechildwasremovedbecauseitsimagewas;SPMamp;;SPMamp;toosimilartoasupposedlydifferentchildttPEAKS_TOO_CLOSE;SPMamp;0x2000000000;SPMamp;Atleastsomepeakswithinthisobjectweretooclosetobedebled,and;SPMamp;;SPMamp;thustheyweremergedintoasinglepeak.ttDEBLEND_UNASSIGNED_FLUX;SPMamp;0x40000000000;SPMamp;Afterdebling,asignificantfractionoffluxwasnotassigned;SPMamp;;SPMamp;toanychildrenttDEBLENDED_AT_EDGE;SPMamp;0x200000000000;SPMamp;Anobjectcloseenoughtotheedgeoftheframethatitnormally;SPMamp;;SPMamp;isnotdebledisdebledanyway.Onlysetforobjectslarge;SPMamp;;SPMamp;enoughtobettEDGEinallfieldsstrips.ttCHILD;SPMamp;0x10;SPMamp;ObjectistheproductofanattempttodeblattBLENDEDobject.ttDEBLENDED_AS_PSF;SPMamp;0x2000000;SPMamp;ThedeblertreatedthisobjectasaPSF.ttDEBLEND_NOPEAK;SPMamp;0x400000000000;SPMamp;Therewasnodetectedpeakwithinthischildinatleastoneband.ttMOVED;SPMamp;0x80000000;SPMamp;Thedebleridentifiedthisobjectaspossiblymoving.ttDEBLENDED_AS_MOVING;SPMamp;0x100000000;SPMamp;AttMOVEDobjectthatthedeblertreatedasmovingttNODEBLEND_MOVING;SPMamp;0x200000000;SPMamp;AttMOVEDobjectthatthedeblerdidnottreatasmovingttTOO_FEW_DETECTIONS;SPMamp;0x400000000;SPMamp;Achildofthisobjectwasnotdetectedinenoughbandstoreliably;SPMamp;;SPMamp;deblasmovingttBAD_MOVING_FIT;SPMamp;0x800000000;SPMamp;Themovingfitwastoopoortobebelievable.ttSTATIONARY;SPMamp;0x1000000000;SPMamp;Thisobjectwasconsistentwithbeingstationary.ttBAD_MOVING_FIT_CHILD;SPMamp;0x20000000000;SPMamp;Apossiblemovingchild'svelocityfitwastoopoor,soitwas;SPMamp;;SPMamp;discardedandtheparentwasnotdebledasmovingttTOO_FEW_GOOD_DETECTIONS;SPMamp;0x1000000000000;SPMamp;Achildofthisobjecthadtoofewgooddetectionstobedebled;SPMamp;;SPMamp;asmovingttPEAKCENTER;SPMamp;0x20;SPMamp;Givencenterispositionofpeakpixel,ratherthan;SPMamp;;SPMamp;basedonthemaximum-likelihoodestimatorttCANONICAL_CENTER;SPMamp;0x1;SPMamp;Measurementsusedthecenterin_inline$r$_inline,ratherthanthelocallydeterminedcenter.ttNOTCHECKED;SPMamp;0x80000;SPMamp;Therearepixelsintheobjectwhichwerenotchecked;SPMamp;;SPMamp;toseeiftheyincludedalocalpeak,suchascoresofsaturatedstarsttMEDIAN_CENTRE;SPMamp;0x4000000000;SPMamp;Centergivenisofmedian-smoothedimagettCENTER_OFF_AIMAGE;SPMamp;0x2000000000000;SPMamp;Atleastonepeak'scenterlayoffoftheatlasimage.Thiscan;SPMamp;;SPMamp;happenwhentheobjectisdebledasmoving,orifthe;SPMamp;;SPMamp;astrometryisbadttNOPETRO;SPMamp;0x100;SPMamp;NovalidPetrosianradiuswasfoundforthisobject.ttMANYPETRO;SPMamp;0x200;SPMamp;MorethanonePetrosianradiuswasfound.ttNOPETRO_BIG;SPMamp;0x400;SPMamp;Petrosianradiusisbeyondthelastpointintheradialprofile.ttPETROFAINT;SPMamp;0x800000;SPMamp;AtleastonepossiblePetrosianradiuswasrejectedasthe;SPMamp;;SPMamp;surfacebrightnessat_inline$r_P$_inlinewastoolow.IfNOPETROisn't;SPMamp;;SPMamp;set,adifferent,acceptablePetrosianradiuswasfound.ttMANYR50;SPMamp;0x2000;SPMamp;Anobjecthasmorethanone50%lightradiusttMANYR90;SPMamp;0x4000;SPMamp;Anobjecthasmorethanone90%lightradiusttBADSKY;SPMamp;0x400000;SPMamp;Theskylevelissobadthatthehighestpixelintheobjectis;SPMamp;;SPMamp;emverynegative;farmoresothanamerenon-detection.;SPMamp;;SPMamp;Nofurtheranalysisisattempted.ttNOPROFILE;SPMamp;0x80;SPMamp;Thisobjectwastoosmallortooclosetothe;SPMamp;;SPMamp;edgetoestimatearadialprofilettTOO_LARGE;SPMamp;0x1000000;SPMamp;Theobjectistoolargeforustomeasureitsprofile(i.e.;SPMamp;;SPMamp;itextsbeyondaradiusofapproximately260arcsec),;SPMamp;;SPMamp;oratleastonechildislargerthanhalfaframettBAD_RADIAL;SPMamp;0x8000;SPMamp;Someofthepointsinthegivenradialprofilehave;SPMamp;;SPMamp;negativesignal-to-noiseratio.Notasignificantparameter.ttINCOMPLETE_PROFILE;SPMamp;0x10000;SPMamp;ThePetrosianradiusintersectstheedgeoftheframettELLIPFAINT;SPMamp;0x8000000;SPMamp;Theobject'scenterisfainterthantheisophotewhose;SPMamp;;SPMamp;shapeisdesired,sotheisophotepropertiesarenotmeasured.;SPMamp;;SPMamp;Alsoflaggedifprofileisincomplete.ttCR;SPMamp;0x1000;SPMamp;Containsapixelinterpretedtobepartofacosmicray.ttINTERP;SPMamp;0x20000;SPMamp;Theobjectcontainsoneormorepixelswhosevalues;SPMamp;;SPMamp;weredeterminedbyinterpolationttINTERP_CENTER;SPMamp;0x100000000000;SPMamp;Theobjectcenterisclosetoatleastoneinterpolatedpixel.ttPSF_FLUX_INTERP;SPMamp;0x800000000000;SPMamp;Greaterthan20%ofthePSFfluxisfrominterpolatedpixels.ttBAD_COUNTS_ERROR;SPMamp;0x10000000000;SPMamp;Anobjectcontaininginterpolatedpixelshadtoofewgoodpixels;SPMamp;;SPMamp;toformareliableestimateofitserror;thequotederror;SPMamp;;SPMamp;maybeunderestimatedttNOSTOKES;SPMamp;0x200000;SPMamp;NoStokesparameterwasmeasured,eitherbecauseofan;SPMamp;;SPMamp;incompleteprofileornumericaldifficulties.data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=613 HEIGHT=340 ALIGN=BOTTOM ALT="deluxetable1753" SRC="img201.gif">|; 
$key = q/{_inline}$approx1%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3375" SRC="img143.gif">|; 
$key = q/{_inline}$2.5^circ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=27 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2827" SRC="img9.gif">|; 
$key = q/{_inline}$r^*approx${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=34 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3211" SRC="img114.gif">|; 
$key = q/{_inline}$Rapprox1800${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=70 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline2809" SRC="img5.gif">|; 
$key = q/{_inline}$512times372${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2849" SRC="img16.gif">|; 
$key = q/{deluxetable}lllrrdeftabletypesizesmalltablewidth0pttablecolumns5tablecaptionSDSSFilterParameterslabeltbl-filter-parameterstableheadcolheadName;SPMamp;colhead_inline$lambda_eff$_inline(AA);SPMamp;colhead_inline$sigma^2$_inline;SPMamp;colheadFWHM(AA);SPMamp;colheadQstartdata_inline$u$_inline;SPMamp;3551;SPMamp;_inline$3.00times10^-3$_inline;SPMamp;581;SPMamp;0.0171_inline$g$_inline;SPMamp;4686;SPMamp;_inline$7.13times10^-3$_inline;SPMamp;1262;SPMamp;0.0893_inline$r$_inline;SPMamp;6166;SPMamp;_inline$3.13times10^-3$_inline;SPMamp;1149;SPMamp;0.0886_inline$i$_inline;SPMamp;7480;SPMamp;_inline$2.58times10^-3$_inline;SPMamp;1237;SPMamp;0.0591_inline$z$_inline;SPMamp;8932;SPMamp;_inline$3.18times10^-3$_inline;SPMamp;994;SPMamp;0.0099data{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=786 HEIGHT=481 ALIGN=BOTTOM ALT="deluxetable2198" SRC="img211.gif">|; 
$key = q/{_inline}$i^*;SPMlt;20.0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3455" SRC="img169.gif">|; 
$key = q/{_inline}$(lambda,eta)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=38 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2905" SRC="img28.gif">|; 
$key = q/{_inline}$4%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3331" SRC="img133.gif">|; 
$key = q/{_inline}$pi${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=10 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline2811" SRC="img6.gif">|; 
$key = q/{_inline}$alpha(2000)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=57 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3125" SRC="img86.gif">|; 
$key = q/{_inline}$zsim2.7${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3447" SRC="img165.gif">|; 
$key = q/{_inline}$approx${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=9 ALIGN=BOTTOM ALT="tex2html_wrap_inline2799" SRC="img3.gif">|; 
$key = q/{figure}plotonefig_ZhistQso_v2.pslabelfig-ZhistQso{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=713 HEIGHT=192 ALIGN=BOTTOM ALT="figure2773" SRC="img243.gif">|; 
$key = q/{_inline}$r^*=17.77${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=79 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3349" SRC="img137.gif">|; 
$key = q/{_inline}$g^*r^*i^*z^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3469" SRC="img172.gif">|; 
$key = q/{_inline}$^-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=9 ALIGN=BOTTOM ALT="tex2html_wrap_inline2861" SRC="img20.gif">|; 
$key = q/{figure}plotonefig_WedgeEqGal_v2.pslabelfig-WedgeEqGal{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=713 HEIGHT=192 ALIGN=BOTTOM ALT="figure2768" SRC="img242.gif">|; 
$key = q/{_inline}$u^*=22.0,g^*=22.2,r^*=22.2,i^*=21.3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=303 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3059" SRC="img68.gif">|; 
$key = q/{_inline}$delta_2000=0arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2909" SRC="img30.gif">|; 
$key = q/{_inline}$(0.65;SPMlt;u^*-g^*;SPMlt;0.9)~and~(0.2;SPMlt;g^*-r^*;SPMlt;0.9)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=335 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3495" SRC="img175.gif">|; 
$key = q/{_inline}$X_rmref=1.3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=76 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3247" SRC="img119.gif">|; 
$key = q/{_inline}$(u'-g')_rmref${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=78 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3249" SRC="img120.gif">|; 
$key = q/{deluxetable}cccctablecaptionAsinhMagnitudeSofteningParameterslabeltbl-bprimetablewidth0pttablecolumns4tablecommentsThesevaluesofthesofteningparameter_inline$b$_inlinearesettobeapproximate1_inline$sigma$_inlineoftheskynoise;thus,onlylowsignal-to-noiseratiomeasurementsareaffectedbythedifferencebetweenasinhandPogsonmagnitudes.Thefinalcolumngivestheasinhmagnitudeassociatedwithanobjectforwhich_inline$ff_0=10b$_inline;thedifferencebetweenPogsonandasinhmagnitudesis_inline$;SPMlt;1%$_inlineforobjectsbrighterthanthis.(Notethatthedefinition_inline$b$_inlinehasbeenmodifiedsinceitsmentionintheAppixofcitefan99b.There,_inline$b$_inlinehadunitsof_inline$DNsec$_inline;now,itisadimensionlessquantity.)tableheadcolheadBand;SPMamp;colhead_inline$b$_inline;SPMamp;colheadZerofluxmagnitude(_inline$m(ff_0=0)$_inline);SPMamp;colhead_inline$m(ff_0=10b)$_inlinestartdata_inline$u$_inline;SPMamp;_inline$1.4times10^-10$_inline;SPMamp;24.63;SPMamp;22.12cr_inline$g$_inline;SPMamp;_inline$0.9times10^-10$_inline;SPMamp;25.11;SPMamp;22.60cr_inline$r$_inline;SPMamp;_inline$1.2times10^-10$_inline;SPMamp;24.80;SPMamp;22.29cr_inline$i$_inline;SPMamp;_inline$1.8times10^-10$_inline;SPMamp;24.36;SPMamp;21.85cr_inline$z$_inline;SPMamp;_inline$7.4times10^-10$_inline;SPMamp;22.83;SPMamp;20.32crdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=657 HEIGHT=476 ALIGN=BOTTOM ALT="deluxetable2291" SRC="img213.gif">|; 
$key = q/{_inline}$mu=alpha${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2947" SRC="img46.gif">|; 
$key = q/{figure}includegraphics[scale=0.8]fig-overlap-errors.pslabelfig-overlap-errors{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=505 HEIGHT=611 ALIGN=BOTTOM ALT="figure2748" SRC="img235.gif">|; 
$key = q/{_inline}$5sigma${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3051" SRC="img66.gif">|; 
$key = q/{_inline}$912,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=24 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3421" SRC="img153.gif">|; 
$key = q/{_inline}$15.0;SPMlt;i^*;SPMlt;19.0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=120 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3443" SRC="img160.gif">|; 
$key = q/{_inline}$r=r_e50${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3135" SRC="img92.gif">|; 
$key = q/{_inline}$5''times8''${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2959" SRC="img51.gif">|; 
$key = q/{_inline}$sim2000${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=51 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3583" SRC="img187.gif">|; 
$key = q/{_inline}$lambda_eff${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2887" SRC="img24.gif">|; 
$key = q/{_inline}$3^circ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2813" SRC="img7.gif">|; 
$key = q/{_inline}$16;SPMlt;r^*;SPMlt;17${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2871" SRC="img23.gif">|; 
$key = q/{_inline}$18;SPMlt;r^*;SPMlt;21.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=109 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3171" SRC="img105.gif">|; 
$key = q/{_inline}$chi^2_dof;SPMlt;2.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=78 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline3563" SRC="img186.gif">|; 
$key = q/{_inline}$i^*=16.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3445" SRC="img161.gif">|; 
$key = q/{_inline}$zapprox0.15${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3403" SRC="img149.gif">|; 
$key = q/{deluxetable}rrltabletypesizefootnotesizetablecaptionImageMaskBitslabeltbl-maskbitstablewidth0pttableheadcolheadHexBit;SPMamp;colheadFlag;SPMamp;colheadExplanationstartdata0x001;SPMamp;INTERP;SPMamp;pixel'svaluehasbeeninterpolated0x002;SPMamp;SATUR;SPMamp;pixeliswassaturated0x004;SPMamp;NOTCHECKED;SPMamp;pixelwasNOTexaminedforanobject0x008;SPMamp;OBJECT;SPMamp;pixelispartofsomeobject0x010;SPMamp;BRIGHTOBJECT;SPMamp;pixelispartofbrightobject0x020;SPMamp;BINOBJECT;SPMamp;pixelispartofbinnedobject0x040;SPMamp;CATOBJECT;SPMamp;pixelispartofacataloguedobject0x080;SPMamp;SUBTRACTED;SPMamp;modelhasbeensubtractedfrompixel0x100;SPMamp;GHOST;SPMamp;pixelispartofaghost0x200;SPMamp;CR;SPMamp;pixelispartofacosmicraydata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=643 HEIGHT=882 ALIGN=BOTTOM ALT="deluxetable1741" SRC="img200.gif">|; 
$key = q/{_inline}$10^-17,rmerg,s^-1,cm^-2,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=137 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2859" SRC="img19.gif">|; 
$key = q/{_inline}$alpha_2000=5arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=77 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2917" SRC="img33.gif">|; 
$key = q/{_inline}$r^*;SPMgt;20.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3123" SRC="img85.gif">|; 
$key = q/{_inline}$r^*=19${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3373" SRC="img142.gif">|; 
$key = q/{deluxetable}rlnormalsizetablecaptionBreakdownofFiberAllocationforaTypicalPlatelabeltbl-fiberallocationtablewidth0pttableheadcolheadNumberofFibers;SPMamp;colheadTargetstartdatabf640;SPMamp;bfTotal32;SPMamp;sky8;SPMamp;spectrophotometricstandards8;SPMamp;reddeningstandards_inline$approx$_inline2;SPMamp;hotsubdwarfstandards_inline$approx$_inline480;SPMamp;galaxies_inline$longrightarrow$_inline;SPMamp;_inline$approx$_inline420inmaingalaxysample;SPMamp;_inline$approx$_inline60inLRGsample_inline$approx$_inline80;SPMamp;quasarcandidates_inline$approx$_inline30;SPMamp;unreserved_inline$longrightarrow$_inline;SPMamp;_inline$approx$_inline5ROSATAll-SkySurveysources;SPMamp;_inline$approx$_inline15stars;SPMamp;_inline$approx$_inline7--8seripityobjects;SPMamp;_inline$approx$_inline2--3qualityassurancetargetsdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=701 HEIGHT=1004 ALIGN=BOTTOM ALT="deluxetable2367" SRC="img218.gif">|; 
$key = q/{_inline}$(mu,nu)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=39 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2941" SRC="img43.gif">|; 
$key = q/{_inline}$2arcsec${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3449" SRC="img167.gif">|; 
$key = q/{_inline}$arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=5 HEIGHT=6 ALIGN=BOTTOM ALT="tex2html_wrap_inline3257" SRC="img123.gif">|; 
$key = q/{_inline}$2times2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=37 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline3053" SRC="img67.gif">|; 
$key = q/{_inline}$alpha${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline3417" SRC="img151.gif">|; 
$key = q/{_inline}$(SN)^2;SPMgt;15${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=94 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline2965" SRC="img52.gif">|; 
$key = q/{figure}plotonefig_ZhistGlx_v2.pslabelfig-ZhistGlx{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=748 HEIGHT=338 ALIGN=BOTTOM ALT="figure2763" SRC="img238.gif">|; 
$key = q/{_inline}$sim40pm20${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3647" SRC="img191.gif">|; 
$key = q/{_inline}$0.20977arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=63 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3343" SRC="img136.gif">|; 
$key = q/{deluxetable}llltabletypesizetinytablecaptionSpectroscopicPlateClasslabeltbl-administrative-platetablewidth0pttablecolumns3tableheadcolheadName;SPMamp;colheadType;SPMamp;colheadDescriptionstartdatahlinevspace-6ptmulticolumn3cnormalsizeClassbfPlate:multicolumn3cPropertiesofspectroscopyplates[4pt]hlineplate_ID;SPMamp;int64;SPMamp;UniqueIDmjd;MJD;SPMamp;int32;SPMamp;MJDofobservationplateID;plateid;SPMamp;int16;SPMamp;PlateIDtileID;tileid;SPMamp;int16;SPMamp;TileIDmapID;mapid;SPMamp;int16;SPMamp;MapIDnExp;nexp;SPMamp;int16;SPMamp;Numberofexposurestai;TAI;SPMamp;float32;SPMamp;TAIsecondsraBoresight;ra_b;SPMamp;float64;SPMamp;RAoftelescopeboresight(degrees)decBoresight;dec_b;SPMamp;float64;SPMamp;DECoftelescopeboresight(degrees)taiHms;taihms;SPMamp;char[20];SPMamp;HMSexpTime;exptime;SPMamp;float32;SPMamp;Totalexposuretime(seconds)expTimeB1;expt_b1;SPMamp;float32;SPMamp;Exposuretimeb1camera(seconds)expTimeB2;expt_b2;SPMamp;float32;SPMamp;Exposuretimeb2camera(seconds)expTimeR1;expt_r1;SPMamp;float32;SPMamp;Exposuretimer1camera(seconds)expTimeR2;expt_r2;SPMamp;float32;SPMamp;Exposuretimer2camera(seconds)helioRV;heliorv;SPMamp;float32;SPMamp;Heliocentricvelocitycorrection(kms)ra;radeg;SPMamp;float64;SPMamp;RAofplatecenter(degrees)dec;decdeg;SPMamp;float64;SPMamp;DECofplatecenter(degrees)htmID;SPMamp;int64;SPMamp;HierarchicalTriangularMeshlevel20IDofplatecentersn1;SN1;SPMamp;float32[3];SPMamp;Signal-to-noiseratioin1stspectrographin_inline$g,r,i$_inlineat20.2sn2;SN2;SPMamp;float32[3];SPMamp;Signal-to-noiseratioin2ndspectrographin_inline$g,r,i$_inlineat20.2reddening;SPMamp;float32[5];SPMamp;Reddeninginallfivebands(mag)dateObs;dateobs;date_obs;SPMamp;char[12];SPMamp;DateofobservationtimeSys;timesys;SPMamp;char[8];SPMamp;Timesystemquality;SPMamp;char[12];SPMamp;Qualityofnightimagename;SPMamp;char[32];SPMamp;Nameoftarget;PlateId-MJD-MapperReRunprogram;SPMamp;char[16];SPMamp;IDofCCDprogramversion;SPMamp;char[20];SPMamp;IOPversionobserver;obsrvr;SPMamp;char[20];SPMamp;ObservernamecamVer;camver;SPMamp;char[20];SPMamp;Cameracodeversionspec2DVer;vers2d;spec2d_ver;spec2d_v;SPMamp;char[20];SPMamp;IDLSpec2DversionutilsVer;versutil;utils_ver;utils_v;SPMamp;char[20];SPMamp;IDLUtilsversionspec1DVer;vers1d;vers_1d;SPMamp;char[20];SPMamp;Spec1DversionreadVer;versread;SPMamp;char[20];SPMamp;Versionofidlspec2dforpre-processingrawdatacombVer;verscomb;SPMamp;char[20];SPMamp;Versionofidlspec2dforcombiningmultiplespectraexpID;SPMamp;int64[];SPMamp;ExposureIDarray.UseexpIDString(i)togetthestring.expIDString(int32);SPMamp;char*;SPMamp;Functiontoretrieveexposureidstringspecobj;spec;SPMamp;ManyAssocxSpecObj;SPMamp;Linktothespectroscopicobjectsonthisplatedata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=640 HEIGHT=300 ALIGN=BOTTOM ALT="deluxetable2135" SRC="img209.gif">|; 
$key = q/{figure}includegraphics[scale=0.7]fig_Seeing_v2.pslabelfig-Seeing{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=505 HEIGHT=611 ALIGN=BOTTOM ALT="figure2728" SRC="img232.gif">|; 
$key = q/{_inline}$mathcalR_P,mathrmlim${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3101" SRC="img78.gif">|; 
$key = q/{_inline}$95arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2945" SRC="img45.gif">|; 
$key = q/{_inline}$;SPMgt;95%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3643" SRC="img190.gif">|; 
$key = q/{_inline}$g^*,r^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=39 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3199" SRC="img109.gif">|; 
$key = q/{_inline}$alpha_2000=95arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=86 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2907" SRC="img29.gif">|; 
$key = q/{_inline}$r^*approx14${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3207" SRC="img113.gif">|; 
$key = q/{_inline}$r^*=20${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=56 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3015" SRC="img55.gif">|; 
$key = q/{deluxetable}rrltabletypesizefootnotesizetablecaptionSpectroscopicMaskBitslabeltbl-spectromasktablewidth0pttableheadcolheadHexBit;SPMamp;colheadFlag;SPMamp;colheadExplanationstartdatamulticolumn3cbfFlagssetontheentirespectrum0x001;SPMamp;NOPLUG;SPMamp;Fibernotlistedinplugmapfile0x002;SPMamp;BADTRACE;SPMamp;Badtraceofflatfield0x004;SPMamp;BADFLAT;SPMamp;Lowcountsinfiberflat0x008;SPMamp;BADARC;SPMamp;Badarcsolution0x010;SPMamp;MANYBADCOLUMNS;SPMamp;_inline$;SPMgt;10%$_inlineofpixelsarebadcolumns0x020;SPMamp;MANYREJECTED;SPMamp;_inline$;SPMgt;10%$_inlineofpixelsarerejectedinextraction0x040;SPMamp;LARGESHIFT;SPMamp;Largespatialshiftbetweenflatandobjectposition0x080;SPMamp;BADSKYFIBER;SPMamp;SkyFibershowsextremeresiduals0x100;SPMamp;NEARWHOPPER;SPMamp;Within2fibersofaverybrightobject0x400;SPMamp;SMEARIMAGE;SPMamp;Smearavailableforredandbluecameras0x800;SPMamp;SMEARHIGHSN;SPMamp;SNsufficientforfullsmearfit0x1000;SPMamp;SMEARMEDSN;SPMamp;SNonlysufficientforscaledmedianfitmulticolumn3cbfFlagssetonsinglepixels0x10000;SPMamp;NEARBADPIXEL;SPMamp;Badpixelwithin3pixelsoftrace0x20000;SPMamp;LOWFLAT;SPMamp;Flatfieldlessthan0.50x40000;SPMamp;FULLREJECT;SPMamp;Pixelfullyrejectedinextraction0x80000;SPMamp;PARTIALREJECT;SPMamp;Somepixelsrejectedinextraction0x100000;SPMamp;SCATTEREDLIGHT;SPMamp;Scatteredlightsignificant0x200000;SPMamp;CROSSTALK;SPMamp;Cross-talksignificant0x400000;SPMamp;NOSKY;SPMamp;Skylevelunknownatthiswavelength0x800000;SPMamp;BRIGHTSKY;SPMamp;Skylevel_inline$;SPMgt;$_inlineflux+10*(fluxerror);SPMamp;;SPMamp;ANDsky_inline$;SPMgt;$_inline1.25*medianskyover99pixels0x1000000;SPMamp;NODATA;SPMamp;NodataavailableincombineB-spline0x2000000;SPMamp;COMBINEREJ;SPMamp;RejectedincombineB-spline0x4000000;SPMamp;BADFLUXFACTOR;SPMamp;Lowflux-calibrationorflux-correctionfactor0x8000000;SPMamp;BADSKYCHI;SPMamp;_inline$chi^2;SPMgt;4$_inlineinskyresidualsatthiswavelength0x10000000;SPMamp;REDMONSTER;SPMamp;Contiguousregionofbad_inline$chi^2$_inlineinskyresidualsdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=760 HEIGHT=998 ALIGN=BOTTOM ALT="deluxetable2005" SRC="img205.gif">|; 
$key = q/{_inline}$zapprox0.45${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=61 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3351" SRC="img138.gif">|; 
$key = q/{_inline}$barg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=9 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline3539" SRC="img185.gif">|; 
$key = q/{_inline}$pm386${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=38 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2937" SRC="img40.gif">|; 
$key = q/{_inline}$r^ast=17.5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3503" SRC="img176.gif">|; 
$key = q/{_inline}$nu${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline2951" SRC="img48.gif">|; 
$key = q/{_inline}$loglambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=34 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3527" SRC="img181.gif">|; 
$key = q/{_inline}$15^circ${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline3215" SRC="img116.gif">|; 
$key = q/{_inline}$320times2048${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=80 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3515" SRC="img180.gif">|; 
$key = q/{_inline}$(alpha,delta)=(0,0)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=100 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2869" SRC="img22.gif">|; 
$key = q/{_inline}$;SPMgt;10%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3043" SRC="img63.gif">|; 
$key = q/{_inline}$alpha_2000=185arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=94 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2915" SRC="img32.gif">|; 
$key = q/{_inline}$RequivlambdaDeltalambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=79 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2953" SRC="img50.gif">|; 
$key = q/{_inline}$|Delta_z|;SPMgt;0.002${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=92 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3653" SRC="img192.gif">|; 
$key = q/{_inline}$(alpha,delta)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=38 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2847" SRC="img15.gif">|; 
$key = q/{_inline}$Delta_COL=col-ttCRPIX1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=165 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3027" SRC="img57.gif">|; 
$key = q/{_inline}$g^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2829" SRC="img10.gif">|; 
$key = q/{_inline}$d(lnlambda)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2893" SRC="img26.gif">|; 
$key = q/{_inline}$i^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3201" SRC="img110.gif">|; 
$key = q/{_inline}$,rlapraise5pthbox$char'074$mathchar;SPMquot;7218,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline2795" SRC="img1.gif">|; 
$key = q/{_inline}$1216,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3419" SRC="img152.gif">|; 
$key = q/{deluxetable}ccccctablecaptionEarlyDataReleaseManualQualitylabeltbl-tbl-qualitytablewidth0pttablecolumns4tableheadcolheadRunNumber;SPMamp;colheadCameraColumn;SPMamp;colheadFields;SPMamp;colheadNewQualitystartdata94;SPMamp;1-6;SPMamp;104-544;SPMamp;ttACCEPTABLE125;SPMamp;1-6;SPMamp;11-451;SPMamp;ttACCEPTABLE752;SPMamp;1-6;SPMamp;11-300;SPMamp;ttACCEPTABLE752;SPMamp;4;SPMamp;339;SPMamp;ttHOLE752;SPMamp;1-6;SPMamp;461-480;SPMamp;ttACCEPTABLE752;SPMamp;1-6;SPMamp;481-483;SPMamp;ttHOLE752;SPMamp;1-6;SPMamp;484-500;SPMamp;ttACCEPTABLE756;SPMamp;1-6;SPMamp;732-802;SPMamp;ttACCEPTABLE1356;SPMamp;1-6;SPMamp;20;SPMamp;ttBAD1356;SPMamp;1-6;SPMamp;21-60;SPMamp;ttACCEPTABLE1356;SPMamp;1-6;SPMamp;91-95;SPMamp;ttACCEPTABLE1359;SPMamp;1-6;SPMamp;19;SPMamp;ttACCEPTABLE1359;SPMamp;3;SPMamp;20;SPMamp;ttHOLE1359;SPMamp;1-6;SPMamp;20-80;SPMamp;ttACCEPTABLEdata{deluxetable}/;
$cached_env_img{$key} = q|<IMG WIDTH=625 HEIGHT=415 ALIGN=BOTTOM ALT="deluxetable2341" SRC="img217.gif">|; 
$key = q/{_inline}$r^*-i^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3299" SRC="img128.gif">|; 
$key = q/{_inline}$u^*-g^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=54 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3467" SRC="img171.gif">|; 
$key = q/{_inline}$5%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3325" SRC="img132.gif">|; 
$key = q/{_inline}$u^*${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline3203" SRC="img111.gif">|; 
$key = q/{_inline}$delta(2000)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=53 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3127" SRC="img87.gif">|; 
$key = q/{_inline}$(lambda,flux)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=65 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2857" SRC="img18.gif">|; 
$key = q/{_inline}$10^-17rm,erg,cm^-2,s^-1,${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=137 HEIGHT=33 ALIGN=MIDDLE ALT="tex2html_wrap_inline3509" SRC="img179.gif">|; 
$key = q/{_inline}$2048times2048${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=89 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2973" SRC="img54.gif">|; 
$key = q/{_inline}$zle0.6${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=52 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3415" SRC="img150.gif">|; 
$key = q/{_inline}$41.5'times41.5'${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=91 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3213" SRC="img115.gif">|; 
$key = q/{_inline}$lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2921" SRC="img35.gif">|; 
$key = q/{_inline}$f(ttstar_L)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3169" SRC="img104.gif">|; 
$key = q/{_inline}$10^-8${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=33 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline3163" SRC="img101.gif">|; 
$key = q/{_inline}$blangleu'-g'rangle${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=67 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3273" SRC="img124.gif">|; 
$key = q/{_inline}$10%${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline3337" SRC="img134.gif">|; 
$key = q/{_inline}$f_lambda${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline3507" SRC="img178.gif">|; 
$key = q/{_inline}$alpha_2000=275arcdeg${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=94 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2911" SRC="img31.gif">|; 

1;

